{% set name = "tabulardelta" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tabulardelta-{{ version }}.tar.gz
  sha256: 38bf155ccc4d171f9009179c6ff404d8df389fb6d71bf2176b48aa865929ea85

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.11
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.11
    - numpy >=1.24.4,<3
    - pandas >=2.0.3,<3

test:
  imports:
    - tabulardelta
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/quantco/tabulardelta
  summary: Simplify table comparisons.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - DominikZuercherQC
    - AaronTacke
